apiVersion: 1

policies:
  - orgId: 1
    receiver: telegram
    group_by: ["alertname", "severity"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: telegram
        match:
          severity: critical
        continue: false
      - receiver: telegram
        match:
          severity: warning
        continue: false
